server:
  port: 8081
#  servlet:
#    context-path: /test
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


obs:
  config-storage:
    endpoint: obs.cn-east-3.myhuaweicloud.com #节点地址
    bucket: mangbo-bucket #存储 Bucket
    accessKey: MLSFTTXPMUP4RR6PCDZ5 #访问 Key
    accessSecret: SdpokEHLns2DneWxtr8ZHjDmwf5NQzKJf4Q760cr #访问 Secret